import Head from 'next/head'
import Header from '../components/Header'

function index() {
  return (
    <div>
      <Head>
        <title>Johnplex's Instagram Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="assets/favicon.ico" />
      </Head>
      {/* Header */}
      <Header/>
      {/* Feed */}
      {/* Modal */}
    </div>
  )
}

export default index
