import Head from 'next/head'
import Header from '../components/Header'
import Feed from '../components/Feed'

function index() {
  return (
    <div className="bg-gray-50 h-screen overflow-y-scroll">
      <Head>
        <title>Johnplex's Instagram Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="assets/favicon.ico" />
      </Head>
      {/* Header */}
      <Header/>
      {/* Feed */}
      <Feed/>
      {/* Modal */}
    </div>
  )
}

export default index
